name: Upload temporary docs to GCP

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  docs-upload-to-gcp-preview:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      checks: "read"
      statuses: "write"
      id-token: "write"
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: sudo apt update -y && sudo apt install -y unzip
      - run: mkdir docs
      - id: download-artifact
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            console.log(github.event);
            var { data } = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = data.artifacts.filter((artifact) => {
              return artifact.name.startsWith("docs-pr-")
            })[0];
            var download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/docs.zip', Buffer.from(download.data));
            return matchArtifact.name.split("-")[2]
      - run: unzip docs.zip -d docs
